version: '2'
services:
    yarn:
        image: node:8.11
        env_file: .env
        entrypoint: yarn
        command: run start:dev
        ports:
            - "8083:8083"
        working_dir: /app
        volumes:
            - .:/app
        links:
            - redis
    redis:
        image: redis:3
        ports:
          - "6379:6379"
